#!/usr/bin/env python 

import classad
import sys
import time

import virtualgridsite.hooks

ad = classad.parseOld(sys.stdin)
newad = virtualgridsite.hooks.update(ad)
if newad:
    print newad.printOld()
sys.exit(0)


