#!/usr/bin/env python 

import classad
import sys
import time

import virtualgridsite.hooks

ad = classad.parseOld(sys.stdin)
hook_cleanup = virtualgridsite.hooks.hook_cleanup(ad)
hook_cleanup.run()
sys.exit(0)


