#!/usr/bin/env python 

import classad
import sys

import virtualgridsite.hooks


stdin = sys.stdin.readlines()
source_ad_content = []   # containts classad from the original job
completed_ad_content = [] # containts classad from the routed completed job
ad = source_ad_content
for line in stdin:
    if line.startswith('------'):
        del ad[-1] # before the ------ line there is also a \n line that needs to be removed
        ad = completed_ad_content
    else:
        ad.append(line)
        
source_ad = classad.parseOld( ''.join(source_ad_content) )
completed_ad = classad.parseOld( ''.join(completed_ad_content) )


newad = virtualgridsite.hooks.exit()
if newad:
    print newad.printOld()
sys.exit(0)

