#!/usr/bin/env python 

import classad
import sys

import virtualgridsite.hooks

incontent = sys.stdin.read()
ads = incontent.split('\n------\n')
# documentation on the input for this HOOK:
#       The source job ClassAd, 
#       followed by the routed copy Classad that completed, 
#       separated by the string "------" and a new line.
source_ad = classad.parseOld(ads[0])
completed_ad = classad.parseOld(ads[1])

newad = virtualgridsite.hooks.exit()
if newad:
    print newad.printOld()
sys.exit(0)

