#!/usr/bin/env python 

import classad
import sys

import virtualgridsite.hooks


route_ad = classad.ClassAd(sys.stdin.readline())
separator_line = sys.stdin.readline()
assert separator_line == "------\n"
ad = classad.parseOld(sys.stdin)
try:
    hook_translate = virtualgridsite.hooks.hook_translate(ad)
    newad = hook_translate.run()
    print newad.printOld(),
    sys.exit(0)
except Exception, ex:
    # FIXME
    # for now, we do not return RC != 0
    # since that does not make HTCondor to cancel the job
    sys.exit(0)

