#!/usr/bin/env python 

import classad
import sys

import virtualgridsite.hooks


route_ad = classad.ClassAd(sys.stdin.readline())
separator_line = sys.stdin.readline()
assert separator_line == "------\n"
ad = classad.parseOld(sys.stdin)
hook_translate = virtualgridsite.hooks.hook_translate(ad)
newad = hook_translate.run()
print newad.printOld(),
sys.exit(0)

