#!/usr/bin/env python 

import classad
import sys
import time

import virtualgridsite.hooks

ad = classad.parseOld(sys.stdin)
try:
    hook_update = virtualgridsite.hooks.hook_update(ad)
    newad = hook_update.run()
    if newad:
        print newad.printOld()
    sys.exit(0)
except Exception, ex:
    # FIXME
    # for now, we do not return RC != 0
    # since that does not make HTCondor to cancel the job
    sys.exit(0)

