#!/usr/bin/env python 

import classad
import sys

import virtualgridsite.hooks


#ad = classad.parseOld(sys.stdin)  
#FIXME
# input is more complex than that
newad = virtualgridsite.hooks.exit()
if newad:
    print newad.printOld()
sys.exit(0)

